name: tool-loadp2
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create release from'     
        required: true
        default: 'master'
jobs:
  build-multiplatform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    steps:
    # Checkout spin2cpp repo and setup environment
    - uses: actions/checkout@v3
      with:
        repository: totalspectrum/loadp2
        ref: ${{ github.event.inputs.branch }}
        submodules: recursive
    - name: Checkout spin2cpp as a tool
      uses: actions/checkout@v3
      with:
        repository: totalspectrum/spin2cpp
        path: ./tools
      # make spin2cpp
    - name: Make spin2cpp
      run: |
        cd ./tools
        make
    # make loadp2
    - name: Make targets
      run: make P2ASM="${{github.workspace}}/tools/build/flexspin -2"
    - name: Create platformio package.json
      run: >
        echo '
        {
          "name": "tool-loadp2",
          "version": "${{ github.event.inputs.branch }}",
          "description": "Propeller uploader",
          "keywords": [
            "uploader",
            "parallax",
            "propeller"
          ],
          "homepage": "https://github.com/totalspectrum/loadp2",
          "license": "GPL-2.0-or-later",
        }
        ' > 'package.json'
    # Create build directory
    - name: Create release directory and copy required files
      run: |
        mkdir 'release'
        mkdir 'release/bin'
        cp package.json release
        cp build/loadp2 release
    # Zip artifacts
    - name: Zip artifact for deployment
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: 'zip'
        directory: 'release'
        path: './'
        filename: loadp2-${{ github.event.inputs.branch }}-${{ runner.os }}-${{ runner.arch }}.zip
    # Uploading build files
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: loadp2-${{ github.event.inputs.branch }}-${{ runner.os }}-${{ runner.arch }}.zip
        path: 'release/loadp2-${{ github.event.inputs.branch }}-${{ runner.os }}-${{ runner.arch }}.zip'
  create-release:
    needs: build-multiplatform
    runs-on: ubuntu-latest
    steps:
    - name: Create artifact dir
      run: mkdir -p ./artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifacts/*/*
        tag_name: loadp2-${{ github.event.inputs.branch }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
